### ISSUE TITLE
Hash results do not match online sha256 calculators

### ISSUE THREAD

**Issue by orodionov** [secworks/sha256#3]
Hi,   I used online sha256 calculators to  convert the values used in the testbech.    Values I got from various online calculators do not match expected value in the test bench.  What could be the problem?

Data:
512'h61626380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000018

Expected hash:
BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD

http://www.xorbin.com/tools/sha256-hash-calculator:
ef37ebb0c25350e946793297d96ae61f6d5332b15f5f682238f6712ae9149430

https://sourceforge.net/projects/hash-calculator/?source=typ_redirect
ef37ebb0c25350e946793297d96ae61f6d5332b15f5f682238f6712ae9149430

**Comment by secworks** [comment]
The problem is that for example xorbin performs the SHA-padding (see FIPS 180-4) on the message. They don't accept a pre-padded block. If you used the message "abc" on xorbin you get the correct expected digest:

ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad
