### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by thibaultmeyer** [secworks/sha256#9]
Hello,

really nice project, but I have a problem with the benchmark part of the readme. I don't understand values,  in a more quantifiable way, for the FPGA devices, what is the rate of hash / seconds ? Or, how to get this number from given informations ?

Sincerely.

**Comment by timkpaine** [comment]
cycles latency is how many cycles it takes to compute the hash, and a few device frequencies are listed. so for the cyclone 4, it can execute 74M cycles per second, and it takes 66 cycles to do the hash, so 74MM C/s / 66 C  = 1.21MM/s. But IDK if this is pipelined or anything, you'll have to ask @secworks. If its pipelined you may be able to do up to 74MM/s

**Comment by thibaultmeyer** [comment]
Niice, thank you.

**Comment by timkpaine** [comment]
You should be aware that none of the fpga devices listed are suitable for crypto mining, and the crypto variants are not well suited for FPGAs atm.

**Comment by secworks** [comment]
timkpaine: Well most crypto algorithms are very well suited to HW implementations. AES for example. If you by "crypto" means cryptocurrency then you are more correct. You scared me security wise. 

The SHA256 core has been used in Bitcoin miners. But the standard version is not pipelined and not optimized for high clock speed. It is quite possible to pipeline the core to increase throughput quite considerably. It is also possible to increase the clock frequency by cutting the longest combinational path (which is in the round function) in half.

Note that the testbenches provided withe core can be used when doing this, so you can work with a baseline.

**Comment by timkpaine** [comment]
@secworks Looking at his github profile I think he wants it for crypto currencies :-)
